### ISSUE TITLE
Unable to build dmtx-utils 0.7.6 on OS X

### ISSUE THREAD

**Issue by mistydemeo** [dmtx/dmtx-utils#5]
When trying to build dmtx-utils 0.7.6 on OS X, I get an error for an undeclared identifier:

```
clang -DHAVE_CONFIG_H -I. -I..  -Wshadow -Wall -pedantic  -I/usr/local/Cellar/libdmtx/0.7.4/include -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.7-35/include/ImageMagick-7 -D_MAGICK_CONFIG_H -g -O2 -c -o ../common/dmtxread_debug-dmtxutil.o `test -f '../common/dmtxutil.c' || echo './'`../common/dmtxutil.c
dmtxread.c:525:36: error: dmtxread.c:use of undeclared identifier 'DmtxPropFnc1'
525:36      err = dmtxDecodeSetProp(dec, DmtxPropFnc1, opt->gs1);
: error:                                    ^
use of undeclared identifier 'DmtxPropFnc1'
      err = dmtxDecodeSetProp(dec, DmtxPropFnc1, opt->gs1);
                                   ^
1 error generated.
1 error generated.
```

This was introduced in c0a1d52b5e0824d6581046700dd2232dbab6b568, which was part of #4.

The full build logs are here: https://gist.github.com/mistydemeo/1822dc29b516cf817b90cd35990d614a

**Comment by mistydemeo** [comment]
I msised that this requires a new version of libdmtx; it's fixed if I upgrade to 0.7.5. Sorry for the noise!

If possible, it'd be great to get a major version bump (e.g., to 0.8.0) if there are new features that a new build would rely on!

**Comment by dmacks** [comment]
If this requires libdmtx>=0.7.5, please update configure.ac. Currently, it has:
```PKG_CHECK_MODULES(DMTX, libdmtx >= 0.7.0, [], AC_MSG_ERROR([dmtxread/dmtxwrite requires libdmtx >= 0.7.0]))```
